# Generated by Django 5.1.5 on 2025-02-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_pricingadjustment_pricingprediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost_price',
        ),
    ]
