# Generated by Django 5.1.5 on 2025-02-06 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_price_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingprediction',
            name='predicted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
