# Generated by Django 5.1.5 on 2025-02-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_order_customer_order_user_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer_rating',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_ratio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
