# Generated by Django 5.1.5 on 2025-02-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_customer_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
