# Generated by Django 5.1.5 on 2025-02-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='customer_rating',
        ),
    ]
